### ISSUE TITLE
WindowTabsSettings.txt in program folder

### ISSUE THREAD

**Issue by hitman72ita** [leafOfTree/WindowTabs#3]
hi, please add an option to save the setings file in the same folder of the main executable, so one can use this app like a portable app. thank you

**Comment by leafOfTree** [comment]
Please try the latest release at https://github.com/leafOfTree/WindowTabs/releases

The settings file in the same folder will be used if present. I've added a button under the Diagnostics tab to copy it from the default location.

![image](https://github.com/user-attachments/assets/c1da7bf5-b026-41e9-9b8f-b49feac1e182)
