### ISSUE TITLE
Could deactivate hotkeys ctrl +1, ctrl+2...?

### ISSUE THREAD

**Issue by joanmibenegas** [leafOfTree/WindowTabs#5]
I need that hotkeys on a program and gets overlap by windowtabs. How could I do it?

**Comment by leafOfTree** [comment]
Thanks for your feedback. Please use the latest release https://github.com/leafOfTree/WindowTabs/releases

I've added an option to deactivate it globally. You will need to restart either WndowTabs or the program after changing it.

![image](https://github.com/user-attachments/assets/c8a4bece-38b9-4d82-aa09-8b8daab5d0e5)
