### ISSUE TITLE
use alt+tab function will easily break down, especially when I use it after the second time or there's a folder opened maybe

### ISSUE THREAD

**Issue by hengxianqin11** [leafOfTree/WindowTabs#8]
![1](https://github.com/user-attachments/assets/e5eca74c-0900-470f-9f70-dc75a0a912e7)
![2](https://github.com/user-attachments/assets/93d92ef6-d6d5-4b56-82d7-b490691cc1e5)

by the way, the first time is ok.

**Comment by hengxianqin11** [comment]
![1](https://github.com/user-attachments/assets/e5eca74c-0900-470f-9f70-dc75a0a912e7)
![2](https://github.com/user-attachments/assets/93d92ef6-d6d5-4b56-82d7-b490691cc1e5)

**Comment by leafOfTree** [comment]
Hi, my test shows that the task switch preview (peek) function causes the breakdown. I don't remember how or if the preview function worked before, so I removed it as a simple solution. https://github.com/leafOfTree/WindowTabs/commit/ee32a836ec4cc96d4ed5faf3f4d727da869cb2f8

Please try the latest release at https://github.com/leafOfTree/WindowTabs/releases

**Comment by hengxianqin11** [comment]
oh,good,it's works.Thank you.
