### ISSUE TITLE
Rough font in WindowTabs UI

### ISSUE THREAD

**Issue by johnd0e** [leafOfTree/WindowTabs#9]
I observe rough highly aliased font in some places of the Settings UI
E.g. programs names (Programs, Workspace), params labels (Appearance, Behavior).
It would be better to apply antialiasing or so.

![image](https://github.com/user-attachments/assets/bd35b118-1955-4e83-ae77-64f97c3e1c92)

Btw, there is no such issue with the original project.

**Comment by leafOfTree** [comment]
Thanks for the report. 
I see that tree nodes and labels have jagged font rendering. Will check on how to apply antialiasing to them.

**Comment by leafOfTree** [comment]
I've applied smooth rendering to font as well as updated layout, background color, etc. to make it look better.

Please check with the latest release at https://github.com/leafOfTree/WindowTabs/releases

![image](https://github.com/user-attachments/assets/044f398f-c521-4f16-9d70-e37137fbf75a)

**Comment by johnd0e** [comment]
> Please check with the latest release at https://github.com/leafOfTree/WindowTabs/releases

But there is no executable attached

**Comment by leafOfTree** [comment]
Oh, forgot to add it. Please check it again.

**Comment by johnd0e** [comment]
Thank you!
The issue is gone.
